In case of success, the backup request was accepted and will be started by the agent.
The response body must always be an empty JSON object.
The broker will poll the `/backup` endpoint to retrieve information the status of the backup.

    + Body

            {
            }