In case of success, the abortion request was accepted. The agent must abort the currently running backup and clean up
all created resources.
The response body must always be an empty JSON object.

    + Body

            {
            }
