In case of success, the request was processed successfully and the sent credentials were deleted. In case
the sent credentials do not exist, `200 OK` must be responded as well (to ensure idempotency). The response
body must always be an empty JSON object.

    + Body

            {
            }