In case of success, the request was processed correctly and the credentials were created.
The response body contains a JSON object with the generated credentials (respecting the
['Binding Credentials' specification of Cloud Foundry](http://docs.cloudfoundry.org/services/binding-credentials.html)).
The example below lists some possible credential fields, though you can provide additional fields as needed.

    + Body

            {
                "hosts":    ["127.0.0.1", "127.0.0.2"],
                "hostname": "127.0.0.1",
                "port":     "8080",
                "uri":      "http://admin:admin@127.0.0.1:1234",
                "username": "admin",
                "password": "admin"
            }