In case of success, the agent has successfully peformed operations required before the service instance gets deprovisioned.
The response body must always be an empty JSON object.

    + Body

            {
            }
