In case of success, the restore request was accepted and will be started by the agent.
The response body must always be an empty JSON object.
The broker will poll the `/restore` endpoint to retrieve information the status of the restore.

    + Body

            {
            }