/*
Copyright 2019 The Service Fabrik Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-broker/interoperator/api/osb/v1alpha1"
	scheme "github.com/cloudfoundry-incubator/service-fabrik-broker/interoperator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SFPlansGetter has a method to return a SFPlanInterface.
// A group's client should implement this interface.
type SFPlansGetter interface {
	SFPlans(namespace string) SFPlanInterface
}

// SFPlanInterface has methods to work with SFPlan resources.
type SFPlanInterface interface {
	Create(ctx context.Context, sFPlan *v1alpha1.SFPlan, opts v1.CreateOptions) (*v1alpha1.SFPlan, error)
	Update(ctx context.Context, sFPlan *v1alpha1.SFPlan, opts v1.UpdateOptions) (*v1alpha1.SFPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SFPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SFPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SFPlan, err error)
	SFPlanExpansion
}

// sFPlans implements SFPlanInterface
type sFPlans struct {
	client rest.Interface
	ns     string
}

// newSFPlans returns a SFPlans
func newSFPlans(c *OsbV1alpha1Client, namespace string) *sFPlans {
	return &sFPlans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sFPlan, and returns the corresponding sFPlan object, and an error if there is any.
func (c *sFPlans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SFPlan, err error) {
	result = &v1alpha1.SFPlan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sfplans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SFPlans that match those selectors.
func (c *sFPlans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SFPlanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SFPlanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sfplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sFPlans.
func (c *sFPlans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sfplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sFPlan and creates it.  Returns the server's representation of the sFPlan, and an error, if there is any.
func (c *sFPlans) Create(ctx context.Context, sFPlan *v1alpha1.SFPlan, opts v1.CreateOptions) (result *v1alpha1.SFPlan, err error) {
	result = &v1alpha1.SFPlan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sfplans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sFPlan).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sFPlan and updates it. Returns the server's representation of the sFPlan, and an error, if there is any.
func (c *sFPlans) Update(ctx context.Context, sFPlan *v1alpha1.SFPlan, opts v1.UpdateOptions) (result *v1alpha1.SFPlan, err error) {
	result = &v1alpha1.SFPlan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sfplans").
		Name(sFPlan.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sFPlan).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sFPlan and deletes it. Returns an error if one occurs.
func (c *sFPlans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sfplans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sFPlans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sfplans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sFPlan.
func (c *sFPlans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SFPlan, err error) {
	result = &v1alpha1.SFPlan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sfplans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
