/*
Copyright 2019 The Service Fabrik Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-broker/interoperator/api/resource/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSFClusters implements SFClusterInterface
type FakeSFClusters struct {
	Fake *FakeResourceV1alpha1
	ns   string
}

var sfclustersResource = schema.GroupVersionResource{Group: "resource", Version: "v1alpha1", Resource: "sfclusters"}

var sfclustersKind = schema.GroupVersionKind{Group: "resource", Version: "v1alpha1", Kind: "SFCluster"}

// Get takes name of the sFCluster, and returns the corresponding sFCluster object, and an error if there is any.
func (c *FakeSFClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SFCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sfclustersResource, c.ns, name), &v1alpha1.SFCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFCluster), err
}

// List takes label and field selectors, and returns the list of SFClusters that match those selectors.
func (c *FakeSFClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SFClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sfclustersResource, sfclustersKind, c.ns, opts), &v1alpha1.SFClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SFClusterList{ListMeta: obj.(*v1alpha1.SFClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.SFClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sFClusters.
func (c *FakeSFClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sfclustersResource, c.ns, opts))

}

// Create takes the representation of a sFCluster and creates it.  Returns the server's representation of the sFCluster, and an error, if there is any.
func (c *FakeSFClusters) Create(ctx context.Context, sFCluster *v1alpha1.SFCluster, opts v1.CreateOptions) (result *v1alpha1.SFCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sfclustersResource, c.ns, sFCluster), &v1alpha1.SFCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFCluster), err
}

// Update takes the representation of a sFCluster and updates it. Returns the server's representation of the sFCluster, and an error, if there is any.
func (c *FakeSFClusters) Update(ctx context.Context, sFCluster *v1alpha1.SFCluster, opts v1.UpdateOptions) (result *v1alpha1.SFCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sfclustersResource, c.ns, sFCluster), &v1alpha1.SFCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSFClusters) UpdateStatus(ctx context.Context, sFCluster *v1alpha1.SFCluster, opts v1.UpdateOptions) (*v1alpha1.SFCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sfclustersResource, "status", c.ns, sFCluster), &v1alpha1.SFCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFCluster), err
}

// Delete takes name of the sFCluster and deletes it. Returns an error if one occurs.
func (c *FakeSFClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sfclustersResource, c.ns, name), &v1alpha1.SFCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSFClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sfclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SFClusterList{})
	return err
}

// Patch applies the patch and returns the patched sFCluster.
func (c *FakeSFClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SFCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sfclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.SFCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFCluster), err
}
