/*
Copyright 2019 The Service Fabrik Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-broker/interoperator/api/osb/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSFServiceBindings implements SFServiceBindingInterface
type FakeSFServiceBindings struct {
	Fake *FakeOsbV1alpha1
	ns   string
}

var sfservicebindingsResource = schema.GroupVersionResource{Group: "osb", Version: "v1alpha1", Resource: "sfservicebindings"}

var sfservicebindingsKind = schema.GroupVersionKind{Group: "osb", Version: "v1alpha1", Kind: "SFServiceBinding"}

// Get takes name of the sFServiceBinding, and returns the corresponding sFServiceBinding object, and an error if there is any.
func (c *FakeSFServiceBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.SFServiceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sfservicebindingsResource, c.ns, name), &v1alpha1.SFServiceBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFServiceBinding), err
}

// List takes label and field selectors, and returns the list of SFServiceBindings that match those selectors.
func (c *FakeSFServiceBindings) List(opts v1.ListOptions) (result *v1alpha1.SFServiceBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sfservicebindingsResource, sfservicebindingsKind, c.ns, opts), &v1alpha1.SFServiceBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SFServiceBindingList{ListMeta: obj.(*v1alpha1.SFServiceBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.SFServiceBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sFServiceBindings.
func (c *FakeSFServiceBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sfservicebindingsResource, c.ns, opts))

}

// Create takes the representation of a sFServiceBinding and creates it.  Returns the server's representation of the sFServiceBinding, and an error, if there is any.
func (c *FakeSFServiceBindings) Create(sFServiceBinding *v1alpha1.SFServiceBinding) (result *v1alpha1.SFServiceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sfservicebindingsResource, c.ns, sFServiceBinding), &v1alpha1.SFServiceBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFServiceBinding), err
}

// Update takes the representation of a sFServiceBinding and updates it. Returns the server's representation of the sFServiceBinding, and an error, if there is any.
func (c *FakeSFServiceBindings) Update(sFServiceBinding *v1alpha1.SFServiceBinding) (result *v1alpha1.SFServiceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sfservicebindingsResource, c.ns, sFServiceBinding), &v1alpha1.SFServiceBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFServiceBinding), err
}

// Delete takes name of the sFServiceBinding and deletes it. Returns an error if one occurs.
func (c *FakeSFServiceBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sfservicebindingsResource, c.ns, name), &v1alpha1.SFServiceBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSFServiceBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sfservicebindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SFServiceBindingList{})
	return err
}

// Patch applies the patch and returns the patched sFServiceBinding.
func (c *FakeSFServiceBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SFServiceBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sfservicebindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SFServiceBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFServiceBinding), err
}
