/*
Copyright 2019 The Service Fabrik Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-broker/interoperator/api/osb/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSFPlans implements SFPlanInterface
type FakeSFPlans struct {
	Fake *FakeOsbV1alpha1
	ns   string
}

var sfplansResource = schema.GroupVersionResource{Group: "osb", Version: "v1alpha1", Resource: "sfplans"}

var sfplansKind = schema.GroupVersionKind{Group: "osb", Version: "v1alpha1", Kind: "SFPlan"}

// Get takes name of the sFPlan, and returns the corresponding sFPlan object, and an error if there is any.
func (c *FakeSFPlans) Get(name string, options v1.GetOptions) (result *v1alpha1.SFPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sfplansResource, c.ns, name), &v1alpha1.SFPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFPlan), err
}

// List takes label and field selectors, and returns the list of SFPlans that match those selectors.
func (c *FakeSFPlans) List(opts v1.ListOptions) (result *v1alpha1.SFPlanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sfplansResource, sfplansKind, c.ns, opts), &v1alpha1.SFPlanList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SFPlanList{ListMeta: obj.(*v1alpha1.SFPlanList).ListMeta}
	for _, item := range obj.(*v1alpha1.SFPlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sFPlans.
func (c *FakeSFPlans) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sfplansResource, c.ns, opts))

}

// Create takes the representation of a sFPlan and creates it.  Returns the server's representation of the sFPlan, and an error, if there is any.
func (c *FakeSFPlans) Create(sFPlan *v1alpha1.SFPlan) (result *v1alpha1.SFPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sfplansResource, c.ns, sFPlan), &v1alpha1.SFPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFPlan), err
}

// Update takes the representation of a sFPlan and updates it. Returns the server's representation of the sFPlan, and an error, if there is any.
func (c *FakeSFPlans) Update(sFPlan *v1alpha1.SFPlan) (result *v1alpha1.SFPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sfplansResource, c.ns, sFPlan), &v1alpha1.SFPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFPlan), err
}

// Delete takes name of the sFPlan and deletes it. Returns an error if one occurs.
func (c *FakeSFPlans) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sfplansResource, c.ns, name), &v1alpha1.SFPlan{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSFPlans) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sfplansResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SFPlanList{})
	return err
}

// Patch applies the patch and returns the patched sFPlan.
func (c *FakeSFPlans) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SFPlan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sfplansResource, c.ns, name, pt, data, subresources...), &v1alpha1.SFPlan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SFPlan), err
}
