{{ $randomString := randAlphaNum 5 | quote -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
  name: provisioner-template
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      control-plane: {{ .Release.Name }}-controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8443"
        prometheus.io/scrape: "true"
      labels:
        control-plane: {{ .Release.Name }}-controller-manager
        rollme: {{ $randomString }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            control-plane: {{ .Release.Name }}-controller-manager
            rollme: {{ $randomString }}
      containers:
      - command:
        - /manager
        args:
        - --metrics-addr=:8443
        - --enable-leader-election
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.interoperator.image.repository }}:{{ .Values.interoperator.image.tag }}"
        imagePullPolicy: {{ .Values.interoperator.image.pullPolicy }}
        name: provisioner
        {{- $resourceSpec := dict }}
        {{- with .Values.interoperator.provisioner.resources }}
          {{- $resourceSpec = deepCopy . }}
        {{- else }}
          {{- with .Values.interoperator.resources }}
            {{- $resourceSpec = deepCopy . }}
          {{- end }}
        {{- end }}
        {{- if not (empty $resourceSpec) }}
        {{- tpl (.Files.Get "conf/resources.yaml") (merge $resourceSpec .) | nindent 8 }}
        {{- end }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 8443
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8443
          name: http
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
  name: {{ .Release.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8443
    targetPort: http
  selector:
    control-plane: {{ .Release.Name }}-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-provisioner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{ .Release.Namespace }}
    # Reference to upper's `metadata.namespace`
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
