apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: {{ .Release.Name }}-controller-manager
    controller-tools.k8s.io: "1.0"
  name: provisioner
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      control-plane: {{ .Release.Name }}-controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: {{ .Release.Name }}-provisioner-controller-manager-service
  replicas: 0
  template:
    metadata:
      labels:
        control-plane: {{ .Release.Name }}-controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.interoperator.image.repository }}:{{ .Values.interoperator.image.tag }}"
        imagePullPolicy: {{ .Values.interoperator.image.pullPolicy }}
        name: manager
        resources:
          limits:
            cpu: {{ .Values.interoperator.resources.limits.cpu }}
            memory: {{ .Values.interoperator.resources.limits.memory }}
          requests:
            cpu: {{ .Values.interoperator.resources.requests.cpu }}
            memory: {{ .Values.interoperator.resources.requests.memory }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9877
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9877
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
      terminationGracePeriodSeconds: 10
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: provisioner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{ .Release.Namespace }}
    # Reference to upper's `metadata.namespace`
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io