apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  broker_username: {{ .Values.broker.username | b64enc }}
  broker_password: {{ .Values.broker.password | b64enc }}
  quota_app_username: {{ .Values.quota_app.username | b64enc }}
  quota_app_password: {{ .Values.quota_app.password | b64enc }}
  {{- if .Values.broker.quota.username }}
  quota_username: {{ .Values.broker.quota.username | b64enc }}
  {{- end }}
  {{- if .Values.broker.quota.password }}
  quota_password: {{ .Values.broker.quota.password | b64enc }}
  {{- end }}
  operator_apis_username: {{ .Values.operator_apis.username | b64enc }}
  operator_apis_password: {{ .Values.operator_apis.password | b64enc }}
  {{- range $k, $v := .Values.broker.quota.regions }}
  {{- range $kk, $vv := $v }}
  {{- if or (eq $kk "username") (eq $kk "password") }}
  {{ printf "region_%s_%s" $k $kk }}: {{ $vv | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
