The request body must be a JSON object with exactly one property containing service-specific credentials the agent is
asked to delete. The individual properties within the `credentials` object depend on the service.

    + Body

            {
                "credentials": {
                    "username": "admin",
                    "dbname": "default"
                }
            }

    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "credentials": {
                        "type": "object",
                        "description": "Service-specific credentials to delete"
                    },
                    "actions": {
                        "type": "object",
                        "description": "The result of the internally executed pre-unbind actions for the service plan"
                    }
                }
            }