The request body must be a JSON object with exactly one property containing user-provided parameters the agent may want
to process/use for its computations. These parameters can be set by the executor of the ```cf bind-service``` or
```cf create-service-key``` command.

    + Body

            {
                "parameters": {
                    "max_connections": 500,
                    "autovacuum": true
                }
            }

    + Schema

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "parameters": {
                        "type": "object",
                        "description": "Service-specific configuration parameters"
                    },
                    "actions": {
                        "type": "object",
                        "description": "The result of the internally executed pre-bind actions for the service plan"
                    }
                }
            }