{
 "title": "Interoperator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AllocatableMemory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster)(interoperator_cluster_allocatable{type=\"memory\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "AllocatableCPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster)(interoperator_cluster_allocatable{type=\"cpu\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Instances Per Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster)(interoperator_cluster_service_instances)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Instance Count By State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==0)",
     "legendFormat": "succeeded"
    },
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==1)",
     "legendFormat": "failed"
    },
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==2)",
     "legendFormat": "in progress"
    },
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==3)",
     "legendFormat": "in_queue/update/delete"
    }
   ]
  },
  {
   "title": "Succeeded Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==0)"
    }
   ]
  },
  {
   "title": "Failed Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==1)"
    }
   ]
  },
  {
   "title": "In Progress Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==2)"
    }
   ]
  },
  {
   "title": "in_queue/update/delete Instance Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "count by (interoperator_service_instances_state) (interoperator_service_instances_state==3)"
    }
   ]
  },
  { "title": "Alerts List", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 5, "y": 33 } }
 ]
}