@startuml
!pragma teoz true
skinparam monochrome false
skinparam sequenceMessageAlign center
skinparam handwritten false
skinparam BoxPadding 30
autoactivate off

title Service Fabrik MCD SFServiceInstance Replicator 

participant Broker
box "Master Cluster" #LightBlue
    collections APIServer
    control MCD_SFServiceInstance_Replicator
end box
box "Sister Cluster" #lightgreen
    collections APIServer as APIServer2
end box

Broker -> APIServer : Create SFServiceInstance
APIServer -> MCD_SFServiceInstance_Replicator ++: Watch event (SFServiceInstance)
MCD_SFServiceInstance_Replicator -> APIServer : Get SFServiceInstance
APIServer --> MCD_SFServiceInstance_Replicator : SFServiceInstance
MCD_SFServiceInstance_Replicator -> MCD_SFServiceInstance_Replicator : Get Target Cluster ID

alt #transparent Cluster ID Not set
    MCD_SFServiceInstance_Replicator --> MCD_SFServiceInstance_Replicator : Return
else Cluster ID is master Cluster
    MCD_SFServiceInstance_Replicator --> MCD_SFServiceInstance_Replicator : Return
else Cluster ID is a diffent Cluster
    MCD_SFServiceInstance_Replicator -> APIServer2 : Create Namepace if deletion not triggered
    MCD_SFServiceInstance_Replicator -> APIServer2 : Trigger delete SFServiceInstance if deletion is \n triggered in master and state is delete
    alt #transparent State is in_queue/update/delete in master
        MCD_SFServiceInstance_Replicator -> APIServer2 : Replicate from master to sister
        MCD_SFServiceInstance_Replicator -> APIServer : Set state as in_progress
    end
    alt #transparent State is in_progress in master
        MCD_SFServiceInstance_Replicator -> APIServer2 : Get SFServiceInstance
        APIServer2 --> MCD_SFServiceInstance_Replicator : SFServiceInstance
        MCD_SFServiceInstance_Replicator -> APIServer : Replicate from sister to master

        alt #transparent State is succeed in sister and last opertion is delete
            MCD_SFServiceInstance_Replicator -> APIServer2 : Trigger deletion of namespace
        end
    end
end
deactivate MCD_SFServiceInstance_Replicator
@enduml