The request body must be an empty JSON object.

    + Body

            {
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {}
            }