In case of a success response, the request was processed successfully and the sent credentials were deleted. In case
the sent credentials do not exist, even `200 OK` must be responded. The response body must always be an empty
JSON object.

    + Body

            {
            }